### ISSUE TITLE
Port to Zope 4

### ISSUE THREAD

**Issue by gforcada** [collective/collective.mockmailhost#6]
This is a (test) dependency of plone.rest(api), and as such, without the dependencies working on Zope 4, there's no way that plone.rest(api) will also work there.

/cc @tisto

**Comment by tisto** [comment]
@gforcada ok, maybe this is something the folks at the alpine sprint could work on. cc @jensens @davilima6

**Comment by davilima6** [comment]
I think it's best to first concentrate on making Plone core compatible with Python 3 and then go for plone.restapi and c.mockmailhost -- once Plone 5.2 is more stable and migration path more clear.

Nevertheless I'll make PRs to apply sixer to both packages, as we did to core during Alpine Sprint.

**Comment by jensens** [comment]
done with #9
